# IBM Verify Configuration
# Generated by Terraform on ${timestamp()}

# Main hostname
IBM_VERIFY_HOSTNAME=${verify_hostname}

# Dashboard and Account URLs
IBM_VERIFY_DASHBOARD_URL=${verify_dashboard}
IBM_VERIFY_ACCOUNT_URL=${verify_account_url}

# API Access URL
# Create API clients at: ${verify_dashboard}security/api-access
IBM_VERIFY_API_ACCESS_URL=${verify_dashboard}security/api-access

# API URLs
IBM_VERIFY_OAUTH_URL=${verify_oauth_url}
IBM_VERIFY_MANAGEMENT_URL=${verify_mgmt_url}

# Credentials
IBM_VERIFY_TENANT_ID=${verify_tenant_id}
IBM_VERIFY_CLIENT_ID=${verify_client_id}
IBM_VERIFY_CLIENT_SECRET=${verify_secret}

# Instance Information
IBM_VERIFY_INSTANCE_ID=${verify_instance_id}

# ============================================================================
# API Client Credentials (Add these after creating API client in console)
# ============================================================================
# IBM_VERIFY_API_CLIENT_ID=your-api-client-id
# IBM_VERIFY_API_CLIENT_SECRET=your-api-client-secret

